export const products = [
  {
    id: 1,
    imageUrl: 'https://source.unsplash.com/6FDXGY9J6y4',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 2,
    imageUrl: 'https://source.unsplash.com/epRFE_hBNjo',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 3,
    imageUrl: 'https://source.unsplash.com/KeGToDVN0l4',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 4,
    imageUrl: 'https://source.unsplash.com/4OHkK555s1A',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 5,
    imageUrl: 'https://source.unsplash.com/R8L1l9RN198',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 6,
    imageUrl: 'https://source.unsplash.com/1VV1MRafd7A',
    category: 'Star Wars',
    name: 'Produto XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 7,
    imageUrl: 'https://source.unsplash.com/8QTZbiQXNqM',
    category: 'Consoles',
    name: 'Controle XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 8,
    imageUrl: 'https://source.unsplash.com/caNzzoxls8Q',
    category: 'Consoles',
    name: 'Controle e console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 9,
    imageUrl: 'https://source.unsplash.com/ZV7lnfyQLmA',
    category: 'Consoles',
    name: 'Console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 10,
    imageUrl: 'https://source.unsplash.com/wa5z9o9fgjw',
    category: 'Consoles',
    name: 'Controle XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 11,
    imageUrl: 'https://source.unsplash.com/Zjn4dT993-g',
    category: 'Consoles',
    name: 'Console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 12,
    imageUrl: 'https://source.unsplash.com/k-xYhI3-gJM',
    category: 'Consoles',
    name: 'Game Boy Color',
    price: 'R$ 60,00',
  },
  {
    id: 13,
    imageUrl: 'https://source.unsplash.com/fMP-oCze3AY',
    category: 'Diversos',
    name: 'Camisa Atari',
    price: 'R$ 60,00',
  },
  {
    id: 14,
    imageUrl: 'https://source.unsplash.com/bUgaIaZysH0',
    category: 'Diversos',
    name: 'Camisa SNES',
    price: 'R$ 60,00',
  },
  {
    id: 15,
    imageUrl: 'https://source.unsplash.com/sYVY_ZKwaxU',
    category: 'Diversos',
    name: 'Controle e console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 16,
    imageUrl: 'https://source.unsplash.com/jMT6BrgBuXU',
    category: 'Diversos',
    name: 'Controle e console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 17,
    imageUrl: 'https://source.unsplash.com/MxVkWPiJALs',
    category: 'Diversos',
    name: 'Controle e console XYZ',
    price: 'R$ 60,00',
  },
  {
    id: 18,
    imageUrl: 'https://source.unsplash.com/r27umXAelDc',
    category: 'Diversos',
    name: 'Controle e console XYZ',
    price: 'R$ 60,00',
  },
]
