import { Header } from '@/components/header'
import './globals.css'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ 
  weight: ['400' ,'500','700'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
