import { Header } from '@/components/header'
import './globals.css'
import { Raleway } from 'next/font/google'
import { ReactNode } from 'react'

const raleway = Raleway({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-raleway',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <Header />
        {children}
      </body>
    </html>
  )
}
